# Generated by Django 5.1.3 on 2024-11-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=700, null=True, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=800, null=True, verbose_name='Subject')),
                ('message', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact Me',
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
